movie_title = input("Movie_Title: ")
seat_type = input("Seat_Type (VIP/Normal): ")
ticket_qty = int(input("Ticket_Quantity: "))
ticket_price = float(input("Ticket_Price: "))
student_discount = int(input("Student_Discount: "))
total = ticket_qty * ticket_price
final_total = total - (total * student_discount / 100)
print("==============================")
print(f"Movie_Title: {movie_title}")
print(f"Seat_Type: {seat_type}")
print(f"Ticket_Quantity: {ticket_qty}$")
print(f"Ticket_Price: {ticket_price}$")
print(f"Student_Discount: {student_discount}%")
print(f"Final_Total: {final_total:.2f}$")
print("==============================")
